version: "3.8"

services:
  php-cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    stdin_open: true
    tty: true
